export const UPDATE_DOCUMENT_CLIENT_HEIGHT = 'UPDATE_DOCUMENT_CLIENT_HEIGHT' // 窗口高度
export const UPDATE_SIDEBAR_FOLD = 'UPDATE_SIDEBAR_FOLD' // 菜单折叠状态
export const UPDATE_MENU_ACTIVE_NAME = 'UPDATE_MENU_ACTIVE_NAME' // 菜单激活状态
export const UPDATE_MAIN_TABS = 'UPDATE_MAIN_TABS' // 路由 mainTabs 
export const UPDATE_MAIN_TABS_ACTIVE_NAME = 'UPDATE_MAIN_TABS_ACTIVE_NAME' // 路由 mainTabsName 

